CREATE EXTENSION IF NOT EXISTS citext;

DROP TABLE IF EXISTS staff CASCADE;
CREATE TABLE staff (
  StaffID BIGSERIAL PRIMARY KEY,
  NationalID VARCHAR(20) NOT NULL UNIQUE,
  WorkEmail CITEXT NOT NULL UNIQUE,
  Mobile VARCHAR(30) NOT NULL UNIQUE,
  FullName TEXT NOT NULL,
  Unit TEXT,
  AnnualSalary NUMERIC(12,2) CHECK (AnnualSalary >= 0)
);

DROP TABLE IF EXISTS enrollment CASCADE;
DROP TABLE IF EXISTS group_offering CASCADE;
CREATE TABLE group_offering (
  SubjectCode VARCHAR(20) NOT NULL,
  GroupNo VARCHAR(10) NOT NULL,
  Term VARCHAR(10) NOT NULL,
  Year INT NOT NULL CHECK (Year >= 1900),
  CreditHours INT NOT NULL CHECK (CreditHours > 0),
  PRIMARY KEY (SubjectCode, GroupNo, Term, Year)
);
CREATE TABLE enrollment (
  StudentNo BIGINT NOT NULL,
  SubjectCode VARCHAR(20) NOT NULL,
  GroupNo VARCHAR(10) NOT NULL,
  Term VARCHAR(10) NOT NULL,
  Year INT NOT NULL,
  Grade VARCHAR(2),
  PRIMARY KEY (StudentNo, SubjectCode, GroupNo, Term, Year),
  FOREIGN KEY (SubjectCode, GroupNo, Term, Year)
    REFERENCES group_offering (SubjectCode, GroupNo, Term, Year)
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS enrollment_student_idx ON enrollment (StudentNo);

DROP TABLE IF EXISTS registration CASCADE;
DROP TABLE IF EXISTS module CASCADE;
DROP TABLE IF EXISTS lecturer CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;
CREATE TABLE faculty (
  DeptCode VARCHAR(10) PRIMARY KEY,
  DeptName TEXT NOT NULL,
  DeanID BIGINT
);
CREATE TABLE lecturer (
  LecturerID BIGSERIAL PRIMARY KEY,
  FullName TEXT NOT NULL,
  DeptCode VARCHAR(10),
  Title TEXT,
  FOREIGN KEY (DeptCode) REFERENCES faculty(DeptCode) ON DELETE SET NULL
);
CREATE TABLE module (
  ModuleID BIGSERIAL PRIMARY KEY,
  Title TEXT NOT NULL,
  Credits INT NOT NULL CHECK (Credits > 0),
  DeptCode VARCHAR(10),
  FOREIGN KEY (DeptCode) REFERENCES faculty(DeptCode) ON DELETE RESTRICT
);
CREATE TABLE student (
  StudentNo BIGSERIAL PRIMARY KEY,
  FullName TEXT NOT NULL,
  Email CITEXT UNIQUE,
  MajorCode VARCHAR(10),
  AcademicAdvisorID BIGINT,
  FOREIGN KEY (MajorCode) REFERENCES faculty(DeptCode) ON DELETE SET NULL,
  FOREIGN KEY (AcademicAdvisorID) REFERENCES lecturer(LecturerID) ON DELETE SET NULL
);
CREATE TABLE registration (
  StudentNo BIGINT NOT NULL,
  ModuleID BIGINT NOT NULL,
  Term VARCHAR(10) NOT NULL,
  Year INT NOT NULL CHECK (Year >= 1900),
  Status TEXT,
  PRIMARY KEY (StudentNo, ModuleID, Term, Year),
  FOREIGN KEY (StudentNo) REFERENCES student(StudentNo) ON DELETE CASCADE,
  FOREIGN KEY (ModuleID) REFERENCES module(ModuleID) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS Treatment CASCADE;
DROP TABLE IF EXISTS Appointment CASCADE;
DROP TABLE IF EXISTS PhysicianOffice CASCADE;
DROP TABLE IF EXISTS PhysicianSpecialty CASCADE;
DROP TABLE IF EXISTS PhysicianPhone CASCADE;
DROP TABLE IF EXISTS PatientPhone CASCADE;
DROP TABLE IF EXISTS PatientAddress CASCADE;
DROP TABLE IF EXISTS InsurancePolicy CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS Clinic CASCADE;
DROP TABLE IF EXISTS Physician CASCADE;
DROP TABLE IF EXISTS Patient CASCADE;
CREATE TABLE Patient (
  PatientNo BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  DOB DATE NOT NULL,
  EmergencyContactName TEXT,
  EmergencyContactPhone TEXT
);
CREATE TABLE PatientAddress (
  AddressID BIGSERIAL PRIMARY KEY,
  PatientNo BIGINT NOT NULL REFERENCES Patient(PatientNo) ON DELETE CASCADE,
  AddressLine TEXT NOT NULL,
  City TEXT NOT NULL,
  Region TEXT,
  Zip TEXT
);
CREATE TABLE PatientPhone (
  PhoneID BIGSERIAL PRIMARY KEY,
  PatientNo BIGINT NOT NULL REFERENCES Patient(PatientNo) ON DELETE CASCADE,
  Phone TEXT NOT NULL,
  Type TEXT
);
CREATE TABLE InsurancePolicy (
  PolicyID BIGSERIAL PRIMARY KEY,
  PatientNo BIGINT NOT NULL REFERENCES Patient(PatientNo) ON DELETE CASCADE,
  Provider TEXT NOT NULL,
  PolicyNumber TEXT NOT NULL,
  UNIQUE (Provider, PolicyNumber)
);
CREATE TABLE Physician (
  PhysicianID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  StartDate DATE NOT NULL
);
CREATE TABLE PhysicianPhone (
  PhoneID BIGSERIAL PRIMARY KEY,
  PhysicianID BIGINT NOT NULL REFERENCES Physician(PhysicianID) ON DELETE CASCADE,
  Phone TEXT NOT NULL,
  Type TEXT
);
CREATE TABLE PhysicianSpecialty (
  PhysicianID BIGINT NOT NULL REFERENCES Physician(PhysicianID) ON DELETE CASCADE,
  Specialty TEXT NOT NULL,
  PRIMARY KEY (PhysicianID, Specialty)
);
CREATE TABLE Clinic (
  ClinicCode VARCHAR(20) PRIMARY KEY,
  Name TEXT NOT NULL,
  Floor TEXT
);
CREATE TABLE Room (
  ClinicCode VARCHAR(20) NOT NULL REFERENCES Clinic(ClinicCode) ON DELETE CASCADE,
  RoomNumber VARCHAR(20) NOT NULL,
  PRIMARY KEY (ClinicCode, RoomNumber)
);
CREATE TABLE PhysicianOffice (
  PhysicianID BIGINT NOT NULL REFERENCES Physician(PhysicianID) ON DELETE CASCADE,
  ClinicCode VARCHAR(20) NOT NULL,
  RoomNumber VARCHAR(20) NOT NULL,
  PRIMARY KEY (PhysicianID, ClinicCode, RoomNumber),
  FOREIGN KEY (ClinicCode, RoomNumber) REFERENCES Room(ClinicCode, RoomNumber) ON DELETE CASCADE
);
CREATE TABLE Appointment (
  AppointmentID BIGSERIAL PRIMARY KEY,
  PatientNo BIGINT NOT NULL REFERENCES Patient(PatientNo) ON DELETE CASCADE,
  PhysicianID BIGINT NOT NULL REFERENCES Physician(PhysicianID) ON DELETE RESTRICT,
  ApptDateTime TIMESTAMP NOT NULL,
  Reason TEXT,
  DurationMin INT CHECK (DurationMin > 0),
  Notes TEXT
);
CREATE TABLE Treatment (
  TreatmentID BIGSERIAL PRIMARY KEY,
  AppointmentID BIGINT NOT NULL REFERENCES Appointment(AppointmentID) ON DELETE CASCADE,
  ProcedureCode TEXT,
  Cost NUMERIC(10,2) CHECK (Cost >= 0),
  FollowUpInstructions TEXT
);

DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Inventory CASCADE;
DROP TABLE IF EXISTS ProductSupplier CASCADE;
DROP TABLE IF EXISTS ProductCategory CASCADE;
DROP TABLE IF EXISTS OrderItem CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS Warehouse CASCADE;
DROP TABLE IF EXISTS Supplier CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS CustomerAddress CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
CREATE TABLE Customer (
  CustomerID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Email CITEXT UNIQUE NOT NULL,
  BillingAddressLine TEXT,
  BillingCity TEXT,
  BillingRegion TEXT,
  BillingZip TEXT
);
CREATE TABLE CustomerAddress (
  AddressID BIGSERIAL PRIMARY KEY,
  CustomerID BIGINT NOT NULL REFERENCES Customer(CustomerID) ON DELETE CASCADE,
  AddressLine TEXT NOT NULL,
  City TEXT NOT NULL,
  Region TEXT,
  Zip TEXT,
  Type TEXT CHECK (Type IN ('shipping','other'))
);
CREATE TABLE "Order" (
  OrderID BIGSERIAL PRIMARY KEY,
  CustomerID BIGINT NOT NULL REFERENCES Customer(CustomerID) ON DELETE RESTRICT,
  OrderDate TIMESTAMP NOT NULL DEFAULT now(),
  Status TEXT,
  ShipToAddressID BIGINT REFERENCES CustomerAddress(AddressID) ON DELETE SET NULL
);
CREATE TABLE Product (
  ProductID BIGSERIAL PRIMARY KEY,
  SKU TEXT UNIQUE NOT NULL,
  Name TEXT NOT NULL,
  Description TEXT
);
CREATE TABLE Category (
  CategoryID BIGSERIAL PRIMARY KEY,
  Name TEXT UNIQUE NOT NULL
);
CREATE TABLE ProductCategory (
  ProductID BIGINT NOT NULL REFERENCES Product(ProductID) ON DELETE CASCADE,
  CategoryID BIGINT NOT NULL REFERENCES Category(CategoryID) ON DELETE CASCADE,
  PRIMARY KEY (ProductID, CategoryID)
);
CREATE TABLE Supplier (
  SupplierID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  ContactEmail CITEXT
);
CREATE TABLE ProductSupplier (
  ProductID BIGINT NOT NULL REFERENCES Product(ProductID) ON DELETE CASCADE,
  SupplierID BIGINT NOT NULL REFERENCES Supplier(SupplierID) ON DELETE CASCADE,
  PRIMARY KEY (ProductID, SupplierID)
);
CREATE TABLE Warehouse (
  WarehouseID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  AddressLine TEXT,
  City TEXT,
  Region TEXT,
  Zip TEXT
);
CREATE TABLE Inventory (
  WarehouseID BIGINT NOT NULL REFERENCES Warehouse(WarehouseID) ON DELETE CASCADE,
  ProductID BIGINT NOT NULL REFERENCES Product(ProductID) ON DELETE CASCADE,
  OnHandQty INT NOT NULL CHECK (OnHandQty >= 0),
  PRIMARY KEY (WarehouseID, ProductID)
);
CREATE TABLE Review (
  ReviewID BIGSERIAL PRIMARY KEY,
  CustomerID BIGINT NOT NULL REFERENCES Customer(CustomerID) ON DELETE CASCADE,
  ProductID BIGINT NOT NULL REFERENCES Product(ProductID) ON DELETE CASCADE,
  OrderID BIGINT NOT NULL REFERENCES "Order"(OrderID) ON DELETE CASCADE,
  Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  ReviewText TEXT,
  ReviewDate DATE NOT NULL DEFAULT CURRENT_DATE,
  UNIQUE (CustomerID, ProductID, OrderID)
);
CREATE TABLE OrderItem (
  OrderID BIGINT NOT NULL REFERENCES "Order"(OrderID) ON DELETE CASCADE,
  LineNo INT NOT NULL,
  ProductID BIGINT NOT NULL REFERENCES Product(ProductID) ON DELETE RESTRICT,
  Qty INT NOT NULL CHECK (Qty > 0),
  UnitPriceAtPurchase NUMERIC(10,2) NOT NULL CHECK (UnitPriceAtPurchase >= 0),
  PRIMARY KEY (OrderID, LineNo)
);

DROP TABLE IF EXISTS Expense CASCADE;
DROP TABLE IF EXISTS Budget CASCADE;
DROP TABLE IF EXISTS RoomReservation CASCADE;
DROP TABLE IF EXISTS EventAttendee CASCADE;
DROP TABLE IF EXISTS Event CASCADE;
DROP TABLE IF EXISTS ClubAdvisor CASCADE;
DROP TABLE IF EXISTS Officer CASCADE;
DROP TABLE IF EXISTS Membership CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS FacultyOrg CASCADE;
DROP TABLE IF EXISTS Club CASCADE;
DROP TABLE IF EXISTS StudentOrg CASCADE;
CREATE TABLE StudentOrg (
  StudentID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Email CITEXT UNIQUE NOT NULL,
  Major TEXT,
  Year INT CHECK (Year BETWEEN 1 AND 10)
);
CREATE TABLE Club (
  ClubID BIGSERIAL PRIMARY KEY,
  Name TEXT UNIQUE NOT NULL,
  Description TEXT
);
CREATE TABLE Membership (
  ClubID BIGINT NOT NULL REFERENCES Club(ClubID) ON DELETE CASCADE,
  StudentID BIGINT NOT NULL REFERENCES StudentOrg(StudentID) ON DELETE CASCADE,
  JoinedOn DATE DEFAULT CURRENT_DATE,
  RoleAtJoin TEXT,
  PRIMARY KEY (ClubID, StudentID)
);
CREATE TABLE Officer (
  ClubID BIGINT NOT NULL REFERENCES Club(ClubID) ON DELETE CASCADE,
  StudentID BIGINT NOT NULL REFERENCES StudentOrg(StudentID) ON DELETE CASCADE,
  Title TEXT NOT NULL,
  TermStart DATE NOT NULL,
  TermEnd DATE,
  PRIMARY KEY (ClubID, StudentID, TermStart)
);
CREATE TABLE FacultyOrg (
  FacultyID BIGSERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Dept TEXT
);
CREATE TABLE ClubAdvisor (
  ClubID BIGINT PRIMARY KEY REFERENCES Club(ClubID) ON DELETE CASCADE,
  FacultyID BIGINT NOT NULL REFERENCES FacultyOrg(FacultyID) ON DELETE RESTRICT
);
CREATE TABLE Room (
  Building TEXT NOT NULL,
  RoomNo TEXT NOT NULL,
  Capacity INT CHECK (Capacity >= 0),
  PRIMARY KEY (Building, RoomNo)
);
CREATE TABLE Event (
  EventID BIGSERIAL PRIMARY KEY,
  ClubID BIGINT NOT NULL REFERENCES Club(ClubID) ON DELETE CASCADE,
  Title TEXT NOT NULL,
  StartsAt TIMESTAMP NOT NULL,
  EndsAt TIMESTAMP NOT NULL,
  Description TEXT
);
CREATE TABLE EventAttendee (
  EventID BIGINT NOT NULL REFERENCES Event(EventID) ON DELETE CASCADE,
  StudentID BIGINT NOT NULL REFERENCES StudentOrg(StudentID) ON DELETE CASCADE,
  RSVPStatus TEXT,
  PRIMARY KEY (EventID, StudentID)
);
CREATE TABLE RoomReservation (
  ReservationID BIGSERIAL PRIMARY KEY,
  EventID BIGINT NOT NULL REFERENCES Event(EventID) ON DELETE CASCADE,
  Building TEXT NOT NULL,
  RoomNo TEXT NOT NULL,
  StartDT TIMESTAMP NOT NULL,
  EndDT TIMESTAMP NOT NULL,
  ExpectedAttendance INT CHECK (ExpectedAttendance >= 0),
  FOREIGN KEY (Building, RoomNo) REFERENCES Room(Building, RoomNo) ON DELETE RESTRICT
);
CREATE TABLE Budget (
  ClubID BIGINT NOT NULL REFERENCES Club(ClubID) ON DELETE CASCADE,
  Year INT NOT NULL,
  Amount NUMERIC(12,2) NOT NULL CHECK (Amount >= 0),
  PRIMARY KEY (ClubID, Year)
);
CREATE TABLE Expense (
  ExpenseID BIGSERIAL PRIMARY KEY,
  ClubID BIGINT NOT NULL REFERENCES Club(ClubID) ON DELETE CASCADE,
  ExpenseDate DATE NOT NULL,
  Amount NUMERIC(12,2) NOT NULL CHECK (Amount >= 0),
  Purpose TEXT,
  ApprovedBy TEXT
);


